### ISSUE TITLE
The noise index

### ISSUE THREAD

**Issue by mxchen-mc** [hhc1997/MSCN#3]
Hi @hhc1997,
I have been working on reproducing the results of MSCN, and I have noticed a discrepancy with your reported results. I am using the noise index provided by DECL. Could you please share the noise indexes you used in your experiments? Additionally, I was wondering if there are any specific training tricks that I might be missing.
Thank you for your assistance.
Best regards!

**Comment by hhc1997** [comment]
Hi, @mxchen-mc,
I use the noise index files and code provided by NCR. It seems that the noise index provided by DECL is more challenging. Specifically, DECL randomly selects a given proportion of visual samples and then randomly permutes all their textual counterparts. While in NCR, although one image may have mismatched texts, it is still likely to have some correctly matched texts.
