### ISSUE TITLE
the meta-data of Flickr30K and MS-COCO

### ISSUE THREAD

**Issue by yul1998** [hhc1997/MSCN#5]
Dear author, thank you for your work. Can you provide the meta-data of Flickr30K and MS-COCO?

**Comment by hhc1997** [comment]
Hello, @yul1998. Please refer to https://github.com/hhc1997/MSCN/issues/2#issuecomment-1566706658

**Comment by yul1998** [comment]
> Hello, @yul1998. Please refer to [#2 (comment)](https://github.com/hhc1997/MSCN/issues/2#issuecomment-1566706658)

Thank you for your prompt reply. I have one other question:
Do you know why this issue occurred during the installation of pomegranate?
![image](https://github.com/hhc1997/MSCN/assets/71552069/18432c67-ccb3-4b52-bad6-48feab8aa1b6)

**Comment by hhc1997** [comment]
> Refer
Hi. Do you follow the steps in https://github.com/hhc1997/MSCN/issues/4#issuecomment-1629952542 ?

**Comment by hhc1997** [comment]
Hi @yul1998 , Do you follow the steps in https://github.com/hhc1997/MSCN/issues/4#issuecomment-1629952542 ?

**Comment by yul1998** [comment]
> Hi @yul1998 , Do you follow the steps in [#4 (comment)](https://github.com/hhc1997/MSCN/issues/4#issuecomment-1629952542) ?

Yes, but the problem still arises.

**Comment by hhc1997** [comment]
> > Hi @yul1998 , Do you follow the steps in [#4 (comment)](https://github.com/hhc1997/MSCN/issues/4#issuecomment-1629952542) ?
> 
> Yes, but the problem still arises.
Sorry, I don't know the solution to this issue.

**Comment by yul1998** [comment]
> > > Hi @yul1998 , Do you follow the steps in [#4 (comment)](https://github.com/hhc1997/MSCN/issues/4#issuecomment-1629952542) ?
> > 
> > 
> > Yes, but the problem still arises.
> > Sorry, I don't know the solution to this issue.

Thank you @hhc1997 very much

**Comment by yul1998** [comment]
> > > > Hi @yul1998 , Do you follow the steps in [#4 (comment)](https://github.com/hhc1997/MSCN/issues/4#issuecomment-1629952542) ?
> > > 
> > > 
> > > Yes, but the problem still arises.
> > > Sorry, I don't know the solution to this issue.
> 
> Thank you @hhc1997 very much
![image](https://github.com/hhc1997/MSCN/assets/71552069/059edff1-c91e-4f02-8f6a-96b240386edf)
I have solved this problem. When installing using the above method, it is important to note that the Cython version is before V3 (you can choose **pip install Cython=0.29**).
