### ISSUE TITLE
Training time cost of MSCN.

### ISSUE THREAD

**Issue by Elfenreigen** [hhc1997/MSCN#6]
Hi~ Thanks for your awesome work! It seems that the training is time-costing. I wanna know how much time it costs to train from scratch on MSCOCO dataset for 50 epochs? Or could you please release your training logs for me to compare epoch by epoch?

**Comment by hhc1997** [comment]
> Hi~ Thanks for your awesome work! It seems that the training is time-costing. I wanna know how much time it costs to train from scratch on MSCOCO dataset for 50 epochs? Or could you please release your training logs for me to compare epoch by epoch?


Hi. Thanks for your interest. It takes about one week for training on the MS-COCO dataset. In fact, we find that training MS-COCO for 20 epochs with a 10 epochs warmup could achieve almost the same results.

**Comment by Elfenreigen** [comment]
Thank you for your in-time reply!
